@Library ("example") _
pipeline {
    agent {label 'test-agent'}

    stages {
        stage('DEV') {
            steps {
                example1()
                example2()
            }
        }
        stage('TEST') {
            steps {
                example1()
                example2()
            }
        }
        stage('QA') {
            steps {
                example1()
                example2()
            }
        }
        stage('PROD') {
            steps {
                example1()
                example2()
            }
        }
    }
}
